disabled_rules:
  - trailing_whitespace
  - function_body_length
  - line_length
  - orphaned_doc_comment
  - nesting

opt_in_rules:
  - let_var_whitespace

file_length:
  warning: 400
  error: 500

type_name:
  min_length: 2

included:
  - GetARock
excluded:
  - GetARock/Global/Supports/AppDelegate.swift
  - GetARock/Global/Supports/SceneDelegate.swift
  - GetARock/Network/Mock/Data/*

identifier_name:
  excluded:
    - id
